export enum LeadStatus {
  LEAD_CREATED = 'LEAD_CREATED',
  DOCUMENTS_PENDING = 'DOCUMENTS_PENDING',
  DOCUMENTS_UPLOADED = 'DOCUMENTS_UPLOADED',
  KYC_IN_PROGRESS = 'KYC_IN_PROGRESS',
  KYC_VERIFIED = 'KYC_VERIFIED',
  UNDERWRITING_QUEUE = 'UNDERWRITING_QUEUE',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENNY_DROP_DONE = 'PENNY_DROP_DONE',
  CAM_GENERATED = 'CAM_GENERATED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ADDITIONAL_DOCS_REQUIRED = 'ADDITIONAL_DOCS_REQUIRED',
  READY_TO_DISBURSE = 'READY_TO_DISBURSE',
  ENACH_PENDING = 'ENACH_PENDING',
  ESIGN_PENDING = 'ESIGN_PENDING',
  DISBURSEMENT_INITIATED = 'DISBURSEMENT_INITIATED',
  DISBURSED = 'DISBURSED',
  TRANSFERRED_TO_LMS = 'TRANSFERRED_TO_LMS',
}

export enum UserRole {
  OPS_AGENT = 'OPS_AGENT',
  UNDERWRITER = 'UNDERWRITER',
  CREDIT_MANAGER = 'CREDIT_MANAGER',
  ADMIN = 'ADMIN',
}

export enum DocumentType {
  PAN_CARD = 'PAN_CARD',
  AADHAAR_FRONT = 'AADHAAR_FRONT',
  AADHAAR_BACK = 'AADHAAR_BACK',
  BANK_STATEMENT = 'BANK_STATEMENT',
  GST_CERTIFICATE = 'GST_CERTIFICATE',
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  ITR = 'ITR',
  BALANCE_SHEET = 'BALANCE_SHEET',
  INVOICE = 'INVOICE',
  TRADE_LICENSE = 'TRADE_LICENSE',
  CANCELLED_CHEQUE = 'CANCELLED_CHEQUE',
  CIBIL_REPORT = 'CIBIL_REPORT',
  CAM_DOCUMENT = 'CAM_DOCUMENT',
  SANCTION_LETTER = 'SANCTION_LETTER',
  LOAN_AGREEMENT = 'LOAN_AGREEMENT',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  UPLOADED = 'UPLOADED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum KycStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  VERIFIED = 'VERIFIED',
  FAILED = 'FAILED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}

export enum BorrowerType {
  DEALER = 'DEALER',
  DISTRIBUTOR = 'DISTRIBUTOR',
  RETAILER = 'RETAILER',
}

export enum LoanProductType {
  WORKING_CAPITAL = 'WORKING_CAPITAL',
  DEALER_FINANCING = 'DEALER_FINANCING',
  INVOICE_DISCOUNTING = 'INVOICE_DISCOUNTING',
}

export enum DisbursementStatus {
  PENDING = 'PENDING',
  INITIATED = 'INITIATED',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum JobName {
  KYC_VERIFICATION = 'kyc.verification',
  BANK_STATEMENT_ANALYSIS = 'bank-statement.analysis',
  BUREAU_FETCH = 'bureau.fetch',
  UNDERWRITING_REPORT = 'underwriting.report',
  CAM_GENERATION = 'cam.generation',
  DISBURSEMENT_INITIATE = 'disbursement.initiate',
  NOTIFICATION_EMAIL = 'notification.email',
  NOTIFICATION_SMS = 'notification.sms',
  NOTIFICATION_WHATSAPP = 'notification.whatsapp',
  LMS_TRANSFER = 'lms.transfer',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}
